### ISSUE TITLE
Why is Finale project in Project Development?

### ISSUE THREAD

**Issue by emmapa** [Academany/FabAcademy-Assessment#10]
In the project development page there is the description of the documentation dedicated to the final project ( final project page - slide - video).

I would move the final project requirements in the specific section, adding here the contents that are still in the handbook doc.

**Comment by wendwarge** [comment]
Done - though we need to include other things to.

**Comment by wendwarge** [comment]
Add things from handbook

**Comment by wendwarge** [comment]
Done
