### ISSUE TITLE
week electronics design: add "test it"

### ISSUE THREAD

**Issue by emmapa** [Academany/FabAcademy-Assessment#11]
the assignment says:
   redraw the echo hello-world board,
      add (at least) a button and LED (with current-limiting resistor)
      check the design rules, make it, and test it
      extra credit: simulate its operation
      extra credit: measure its operation

In our doc, we miss the "test" part.

**Comment by TheBeachLab** [comment]
Neil Said test that at least is not shorted and you can upload a program 
to the MC.

But we are not going to fail them if they don't do that, since 
functionality is evaluated 2 weeks from now.

Bas, you proposed that. What should we do?

Fran

**Comment by emmapa** [comment]
I think they should at least try....otherwise the "test it" shouldn't be part of the assignment description.

If the student has no time to do it this week, anyhow they will have to program it. In this case I would ask to the student to write in the documentation that the "test it" need to be done and add the link to that page. Do you think it could work?

**Comment by wendwarge** [comment]
It's semantics. They will have to test it at some point... Students will point forwards and backwards to their two pages if they have problems, instructors will check both pages, as will global eval team.

**Comment by emmapa** [comment]
yep, for me it's clear.
So I would leave it like it is right now and I would close this issue.

**Comment by wendwarge** [comment]
I put in "test if you have time" a few hours ago. closing...closing...closed
