### ISSUE TITLE
week Electronics Production - programming?

### ISSUE THREAD

**Issue by emmapa** [Academany/FabAcademy-Assessment#12]
Is the programming of the ISPprogrammer a requirement?
It looks like in the assignment description...at least it's mentioned, last line.

It's not included in the description in the book, should we add it in the first paragraph?

**Comment by wendwarge** [comment]
The assignment is generally written by Neil, in one sentence, so I tend to leave it alone. It's also written in the beginning of the assignment doc that we don't change assignments after the students have started working on them.

**Comment by emmapa** [comment]
you are right!
anyhow the mismatch between Neil's description and the doc could be confusing.

The potential misunderstanding is similar to the electronic design week, at some point the student will try to program it and point to the right page.

I would just complete the doc definition of the assignment, even if the week is already gone.
Neil's page was updated and the assessment doc wasn't during that week.

**Comment by wendwarge** [comment]
done
