### ISSUE TITLE
Group Final Project 

### ISSUE THREAD

**Issue by emmapa** [Academany/FabAcademy-Assessment#15]
I can't find the description of how to manage a group final project.
Maybe we can add it to the FAQ.

Development of a group final project:
- each student of the group need to prove mastery of the skills gained during the program.
- each student need to develop a part of the whole project with: her/his own design, include a fabbed input device and an output device of your own design, include other components made with additive and subtractive techniques, include 2D and 3D design elements

Final presentation of a group final project:
- each student has to make a specific slide that shows the parts developed by her/him
- one single shared slide for all the students is not good, the slide has to show what the student has made.
- video....

**Comment by wendwarge** [comment]
Good idea, done! Some of this is in the Handbook, but it's better in the assessment doc
