### ISSUE TITLE
Clearify Molding and Casting Assignment

### ISSUE THREAD

**Issue by ARKopp** [Academany/FabAcademy-Assessment#24]
Moulding and Casting

Design a 3D mould, machine it, and cast parts from it.

Learning outcomes:

Design appropriate objects within the limitations of 3 axis machining

Demonstrate workflows used in mould design, construction and casting

Change to
Design a 3D mould, machine it with a cnc milling machine, and cast parts from it.

Learning outcomes:

Design appropriate objects within the limitations of 3 axis machining (not a 3D printer!)

Demonstrate workflows used in mould design, construction and casting

**Comment by TheBeachLab** [comment]
I don't get this modification Andreas. I think that it is clear that a 3D printer cannot machine objects.
Machine it with a CNC milling machine? Isn't it like screw it with a screwdriver?

**Comment by ARKopp** [comment]
the issue is that machine can be misinterpreted as 3D printing. a 3D
printer is also a machine.

**Comment by TheBeachLab** [comment]
Updated the section and the FAQ
