### ISSUE TITLE
question: Computer-Controlled Cutting - group assignment

### ISSUE THREAD

**Issue by emmapa** [Academany/FabAcademy-Assessment#5]
Reading the description of the group assignment I understand it doesn't need to be parametric.
Is it correct?

**Comment by wendwarge** [comment]
Yes but no but yeah. Given that the project has to be parametric anyway, why not start as you have to continue?

**Comment by emmapa** [comment]
I agree, I will suggest to the students to do so, all parametric but...
I only would like to avoid that, during the evaluation phase, instructors complain because the group assignment was not parametric and students complain because it was not specified in the assessment doc.

**Comment by wendwarge** [comment]
@madouc confirmed change with Prof G
